// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef GUIFormGenerator_h
#define GUIFormGenerator_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Browser.H>

class GUIFormGenerator {
public:
  GUIFormGenerator();
  Fl_Window *wIndex;
  Fl_Button *btnNew_wI;
  Fl_Button *btnOpen_wI;
  Fl_Button *btnQuit_wI;
  Fl_Box *boxLogo;
  Fl_Double_Window *wNewProject;
  Fl_Input *input_wNP;
  Fl_Button *btnCancel_wNP;
  Fl_Button *btnNew_wNP;
  Fl_Double_Window *wOpenProject;
  Fl_File_Browser *browserProjects;
  Fl_Button *btnCancel_wOP;
  Fl_Button *btnOpen_wOP;
  Fl_Window *wEditProject;
  Fl_Menu_Bar *menu;
  static Fl_Menu_Item menu_menu[];
  static Fl_Menu_Item *menuSave_wEP;
  static Fl_Menu_Item *menuGenerate_wEP;
  Fl_Input *inputTitle;
  Fl_Browser *browserInputs;
  Fl_Button *btnEditTitle_wEP;
  Fl_Button *btnSave_wEP;
  Fl_Button *btnAdd_wEP;
  Fl_Button *btnEdit_wEP;
  Fl_Button *btnQuit_wEP;
  Fl_Button *btnRemove_wEP;
  Fl_Double_Window *wInputText;
  Fl_Input *inputLabel_wIT;
  Fl_Input *inputID_wIT;
  Fl_Button *btnSave_wIT;
  Fl_Button *btnCancel_wIT;
  Fl_Double_Window *wInputSelect;
  Fl_Input *inputLabel_wIS;
  Fl_Input *inputID_wIS;
  Fl_Button *btnSave_wIS;
  Fl_Button *btnCancel_wIS;
  Fl_Browser *browserOp_wIS;
  Fl_Button *btnAddOp_wIS;
  Fl_Button *btnRemoveOp_wIS;
  Fl_Double_Window *wInputRadio;
  Fl_Input *inputLabel_wIR;
  Fl_Input *inputID_wIR;
  Fl_Button *btnSave_wIR;
  Fl_Button *btnCancel_wIR;
  Fl_Browser *browserOp_wIR;
  Fl_Button *btnAddOp_wIR;
  Fl_Button *btnRemoveOp_wIR;
};
#endif
