// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef RandomDemo_h
#define RandomDemo_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class RandomDemo {
public:
  RandomDemo();
  Fl_Window *w;
  Fl_Input *inputParticipantes;
  Fl_Button *btnReset;
  Fl_Button *btnSortear;
  Fl_Box *boxNrSorteado;
  Fl_Box *boxNrGanhador;
  Fl_Box *boxLogo;
  Fl_Window *wError;
  Fl_Button *btnCloseError;
  Fl_Box *boxError;
};
#endif
